name: Deploy PROD innovation-hub.ca.gov
on:
  push:
    branches:
      - main

jobs:
  build_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: n1hility/cancel-previous-runs@v2
        with: 
          token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/checkout@v3.0.0
      - name: Use Node.js 16.13.1
        uses: actions/setup-node@v1
        with:
          node-version: 16.13.1
      - name: Build 11ty
        run: |
          mkdir _site
          mkdir _site_dist
          npm install --legacy-peer-deps
          npm run build

      # # Push built site files to S3 production bucket
      # - name: Configure AWS Credentials
      #   uses: aws-actions/configure-aws-credentials@v2
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: us-west-1


      # - name: Deploy to S3
      #   run: aws s3 sync --follow-symlinks --delete ./_site s3://innovation-hub.ca.gov

      # Invalidate Cloudfront production distribution
      # - name: invalidate
      #   uses: chetan/invalidate-cloudfront-action@v1.3
      #   env:
      #     DISTRIBUTION: 'E2N488BHQIJRCV'
      #     PATHS: '/*'
      #     AWS_REGION: 'us-west-1'
      #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}                       